services:
  web:
    image: ghcr.io/bramsuurdje/better-paperless-ai:latest
    pull_policy: always
    init: true
    restart: unless-stopped
    env_file:
      - path: .env.local
        required: false
    ports:
      - "3000:3000"
    volumes:
      - app-data:/data

volumes:
  app-data:
